#!/usr/bin/env node
/**
 * Throwaway Ed25519 key material for Profile 0 / 1A development (GUARDRAILS Part 4 "Credentials",
 * execution plan ground rule 5). Prints environment lines grouped by the service that may hold
 * each value; nothing is written to disk. Paste into the gitignored env files and never into
 * Vercel, GitHub or any live profile.
 *
 * Formats match libs/contracts/src/config/env.ts: private keys as PKCS#8 DER hex, public keys as
 * raw 32-byte hex (the same encoding libs/contracts/src/signing/ed25519.ts exports).
 *
 *   node tools/dev-keys.mjs
 */
import { webcrypto } from 'node:crypto';

const hex = (buf) => Buffer.from(buf).toString('hex');

async function pair() {
  const kp = await webcrypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
  const pkcs8 = hex(await webcrypto.subtle.exportKey('pkcs8', kp.privateKey));
  const pub = hex(await webcrypto.subtle.exportKey('raw', kp.publicKey));
  const keyIdBytes = new Uint8Array(await webcrypto.subtle.digest('SHA-256', Buffer.from(pub, 'hex')));
  return { pkcs8, pub, keyId: `ed25519:${hex(keyIdBytes).slice(0, 32)}` };
}

const projection = await pair(); // worker state-projector role
const risk = await pair(); // risk-authorizer
const emergency = await pair(); // operator tooling only

const lines = [
  '# --- generated by tools/dev-keys.mjs — THROWAWAY DEVELOPMENT KEYS, Profile 0/1A only ------------',
  `# generated ${new Date().toISOString()}`,
  '',
  '# worker (deploy/profile-0/.env.worker or .env.local)',
  `PROJECTION_SIGNING_KEY_PKCS8=${projection.pkcs8}`,
  `PROJECTION_SIGNING_PUBLIC_KEY=${projection.pub}`,
  `EMERGENCY_OPERATOR_PUBLIC_KEYS=${emergency.pub}`,
  '',
  '# risk-authorizer (deploy/profile-0/.env.risk-authorizer)',
  `RISK_AUTHORIZATION_KEY_PKCS8=${risk.pkcs8}`,
  `RISK_AUTHORIZATION_PUBLIC_KEY=${risk.pub}`,
  `PROJECTION_VERIFICATION_PUBLIC_KEYS=${projection.pub}`,
  '',
  '# execution-service (deploy/profile-0/.env.execution-service)',
  `RISK_AUTHORIZER_PUBLIC_KEYS=${risk.pub}`,
  `EMERGENCY_OPERATOR_PUBLIC_KEYS=${emergency.pub}`,
  `# key ids for EXECUTOR_GUARDRAILS_JSON: acceptedRiskAuthorizerKeyIds=["${risk.keyId}"], acceptedEmergencyOperatorKeyIds=["${emergency.keyId}"]`,
  '',
  '# operator tooling ONLY — never in any service env file (D25 plane 1 / GUARDRAILS Part 4)',
  `# EMERGENCY_OPERATOR_KEY_PKCS8=${emergency.pkcs8}`,
];
console.log(lines.join('\n'));
