#!/usr/bin/env node
/**
 * Throwaway Ed25519 key material for Profile 0 / 1A development (GUARDRAILS Part 4 "Credentials",
 * execution plan ground rule 5). Prints environment lines grouped by the service that may hold
 * each value; nothing is written to disk. Paste into the gitignored env files and never into
 * Vercel, GitHub or any live profile.
 *
 * Formats match libs/contracts/src/config/env.ts: private keys as PKCS#8 DER hex, public keys as
 * raw 32-byte hex (the same encoding libs/contracts/src/signing/ed25519.ts exports).
 *
 *   node tools/dev-keys.mjs
 */
import { randomBytes, webcrypto } from 'node:crypto';

const hex = (buf) => Buffer.from(buf).toString('hex');

async function pair() {
  const kp = await webcrypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']);
  const pkcs8 = hex(await webcrypto.subtle.exportKey('pkcs8', kp.privateKey));
  const pub = hex(await webcrypto.subtle.exportKey('raw', kp.publicKey));
  const keyIdBytes = new Uint8Array(await webcrypto.subtle.digest('SHA-256', Buffer.from(pub, 'hex')));
  return { pkcs8, pub, keyId: `ed25519:${hex(keyIdBytes).slice(0, 32)}` };
}

const projection = await pair(); // worker state-projector role
const risk = await pair(); // risk-authorizer
const emergency = await pair(); // operator tooling only

/**
 * The shared secret the worker presents to the two internal APIs. Not a signing key and not a
 * capability: it authenticates the caller on a loopback socket, so one value shared by the three
 * processes is the right shape. The worker holds it as INTERNAL_API_SECRET (one value) and each
 * service accepts it in INTERNAL_API_SECRETS (a comma-separated list, so it can be rotated by
 * appending the new value, restarting the services, then moving the worker over).
 * `libs/contracts/src/config/env.ts` requires 64+ hex characters.
 */
const internalApiSecret = hex(randomBytes(32));

const lines = [
  '# --- generated by tools/dev-keys.mjs — THROWAWAY DEVELOPMENT KEYS, Profile 0/1A only ------------',
  `# generated ${new Date().toISOString()}`,
  '',
  '# worker (deploy/profile-0/.env.worker or .env.local)',
  `PROJECTION_SIGNING_KEY_PKCS8=${projection.pkcs8}`,
  `PROJECTION_SIGNING_PUBLIC_KEY=${projection.pub}`,
  `EMERGENCY_OPERATOR_PUBLIC_KEYS=${emergency.pub}`,
  '# Reaching the two internal APIs. Needed for the readiness drills DB_DOWN_EMERGENCY_CLOSE and',
  '# PERSIST_BEFORE_SUBMIT_DRILL, which record FAIL:EXECUTOR_NOT_CONFIGURED without them, and for the',
  '# journal-import role. The live-entry role additionally needs a LIVE account (Profile 2).',
  'EXECUTION_SERVICE_URL=http://127.0.0.1:8791',
  'RISK_AUTHORIZER_URL=http://127.0.0.1:8781',
  `INTERNAL_API_SECRET=${internalApiSecret}`,
  '',
  '# risk-authorizer (deploy/profile-0/.env.risk-authorizer)',
  `RISK_AUTHORIZATION_KEY_PKCS8=${risk.pkcs8}`,
  `RISK_AUTHORIZATION_PUBLIC_KEY=${risk.pub}`,
  `PROJECTION_VERIFICATION_PUBLIC_KEYS=${projection.pub}`,
  'INTERNAL_API_LISTEN=127.0.0.1:8781',
  `INTERNAL_API_SECRETS=${internalApiSecret}`,
  '',
  '# execution-service (deploy/profile-0/.env.execution-service)',
  `RISK_AUTHORIZER_PUBLIC_KEYS=${risk.pub}`,
  `EMERGENCY_OPERATOR_PUBLIC_KEYS=${emergency.pub}`,
  'INTERNAL_API_LISTEN=127.0.0.1:8791',
  'OUT_OF_BAND_LISTEN=127.0.0.1:8792',
  `INTERNAL_API_SECRETS=${internalApiSecret}`,
  `# key ids for EXECUTOR_GUARDRAILS_JSON: acceptedRiskAuthorizerKeyIds=["${risk.keyId}"], acceptedEmergencyOperatorKeyIds=["${emergency.keyId}"]`,
  '',
  '# operator tooling ONLY — never in any service env file (D25 plane 1 / GUARDRAILS Part 4)',
  `# EMERGENCY_OPERATOR_KEY_PKCS8=${emergency.pkcs8}`,
];
console.log(lines.join('\n'));
